name: Deploy Frontend

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [trigger-frontend-build]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DATA_DIR: data
      DEPLOYMENT_BRANCH: github-pages-deployment
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Update deployment branch with frontend build
        run: |
          # Checkout deployment branch if it exists
          git fetch origin
          if git rev-parse --verify origin/${{ env.DEPLOYMENT_BRANCH }} > /dev/null 2>&1; then
            git checkout ${{ env.DEPLOYMENT_BRANCH }}
          else
            # Create new orphan branch if it doesn't exist
            git checkout --orphan ${{ env.DEPLOYMENT_BRANCH }}
            git rm -rf .
          fi
          
          # Preserve data directory if it exists
          if [ -d "${{ env.DATA_DIR }}" ]; then
            mkdir -p /tmp/data-backup
            cp -r ${{ env.DATA_DIR }}/* /tmp/data-backup/
          fi
          
          # Clean the working directory except for .git
          find . -mindepth 1 -path ./.git -prune -o -exec rm -rf {} \; 2> /dev/null || true
          
          # Restore data directory
          if [ -d "/tmp/data-backup" ]; then
            mkdir -p ${{ env.DATA_DIR }}
            cp -r /tmp/data-backup/* ${{ env.DATA_DIR }}/
          fi
          
          # Copy frontend build files
          cp -r ./frontend/build/* .
          
          # Commit and push changes
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit for frontend build."
          else
            git commit -m "Update frontend build"
            git push origin ${{ env.DEPLOYMENT_BRANCH }}
          fi